package pt.arquivo.imagesearch.indexing.utils;

public class MimeTypeCounters {


    public enum PAGE_INDEXER_COUNTERS_REPORTED {
        application_msword,
        application_pdf,
        application_postscript,
        application_rss_xml,
        application_vnd_ms_excel,
        application_vnd_ms_powerpoint,
        application_vnd_oasis_opendocument_text,
        application_vnd_oasis_opendocument_text_template,
        application_vnd_oasis_opendocument_text_master,
        application_vnd_oasis_opendocument_text_web,
        application_vnd_oasis_opendocument_presentation,
        application_vnd_oasis_opendocument_presentation_template,
        application_vnd_oasis_opendocument_spreadsheet,
        application_vnd_oasis_opendocument_spreadsheet_template,
        application_vnd_sun_xml_calc,
        application_vnd_sun_xml_calc_template,
        application_vnd_sun_xml_impress,
        application_vnd_sun_xml_impress_template,
        application_vnd_sun_xml_writer,
        application_vnd_sun_xml_writer_template,
        application_xhtml_xml,
        application_x_bzip2,
        application_x_gzip,
        application_x_kword,
        application_x_kspread,
        application_x_shockwave_flash,
        application_zip,
        text_html,
        text_plain,
        text_richtext,
        text_rtf,
        text_sgml,
        text_tab_separated_values,
        text_xml,
        unknown,
        other,
    }


    public enum PAGE_INDEXER_COUNTERS_DETECTED {
        application_msword,
        application_pdf,
        application_postscript,
        application_rss_xml,
        application_vnd_ms_excel,
        application_vnd_ms_powerpoint,
        application_vnd_oasis_opendocument_text,
        application_vnd_oasis_opendocument_text_template,
        application_vnd_oasis_opendocument_text_master,
        application_vnd_oasis_opendocument_text_web,
        application_vnd_oasis_opendocument_presentation,
        application_vnd_oasis_opendocument_presentation_template,
        application_vnd_oasis_opendocument_spreadsheet,
        application_vnd_oasis_opendocument_spreadsheet_template,
        application_vnd_sun_xml_calc,
        application_vnd_sun_xml_calc_template,
        application_vnd_sun_xml_impress,
        application_vnd_sun_xml_impress_template,
        application_vnd_sun_xml_writer,
        application_vnd_sun_xml_writer_template,
        application_xhtml_xml,
        application_x_bzip2,
        application_x_gzip,
        application_x_kword,
        application_x_kspread,
        application_x_shockwave_flash,
        application_zip,
        text_html,
        text_plain,
        text_richtext,
        text_rtf,
        text_sgml,
        text_tab_separated_values,
        text_xml,
        unknown,
        other,
    }
}